name: Build and Deploy
on: 
  push:
    tags:
      - "**"
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      
      - name: Install deps 🏗
        run: bun i
      - name: Build Frontend 🔨
        run: bun run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
